<nav class="backgroundcolor">
  <a href="index.php"><img class="logo" src="images/logo.png" alt="logo"></a>
  <ul>
        <li class="expand"></li>
        <li class="items"><a href="index.php">Home</a></li>
        <li class="items"><a href="jobs.php">Jobs</a></li>
        <li class="items"><a href="apply.php">Apply</a></li>
        <li class="items"><a href="about.php">About Us</a></li>
        <li class="items"><a href="enhancements.php">Enhancements</a></li>
        <li class="items"><a href="video.php">Video</a></li>
  </ul>
</nav>
