<footer>
        <div class="footer-column" id="f-col1">
            <h3>CODE CRAFTERS</h3>
            <p> 
                Our goal is to provide innovative software solutions to our clients that are user-friendly, 
                secure, and scalable. We strive to deliver a high level of customer 
                experience through excellent customer service and support.</p>
        </div>
        <div class="footer-column" id="f-col2">
            <h3>CONTACTS</h3>
            <ul>
                <li><a href=#></a>Hawthorn, Victoria 3122 </li>
                <li><a href=#></a>Phone: 0491764882</li>
                <li><a href=#></a>Email: CodeCrafters@gmail.com</li>
                <li><a href="mailto:104584773@student.swin.edu.au">
                    104584773@student.swin.edu.au
                </a></li>
            </ul>
        </div>
        <div class="footer-column" id="f-col3">
            <h3>FOLLOW US</h3>
            <ul>
                <li><a href="https://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
                <li><a href="https://instagram.com"><i class="fa fa-instagram"></i></a></li>
                <li><a href="https://twitter.com"><i class="fa fa-twitter"></i></a></li>
            </ul>
        </div>
    </footer>